const traders = {
  example_trader:{name:'Example Trader',initials:'ET',score:87,trades:'1,284',followers:'8.4k',freshness:'12 min ago',wallets:[['SOLANA','7xKp…91mQ'],['EVM','0x8a4f…e21B']],pnl:{'24h':125,'7d':125,'30d':842,all:3210},connections:['example_alex','example_casey','example_lee']},
  example_alex:{name:'Alex Rivera',initials:'AR',score:78,trades:'642',followers:'3.1k',freshness:'24 min ago',wallets:[['SOLANA','4pLm…0k8x']],pnl:{'24h':94,'7d':410,'30d':664,all:1880},connections:['example_trader','example_casey']},
  example_casey:{name:'Casey North',initials:'CN',score:72,trades:'392',followers:'2.8k',freshness:'41 min ago',wallets:[['EVM','0x1c2a…55f9']],pnl:{'24h':-32,'7d':186,'30d':521,all:1102},connections:['example_trader','example_alex']},
  example_lee:{name:'Lee Onchain',initials:'LO',score:65,trades:'211',followers:'1.2k',freshness:'1 hr ago',wallets:[['SOLANA','9vQs…f02L'],['EVM','0xba91…04cD']],pnl:{'24h':52,'7d':98,'30d':210,all:744},connections:['example_trader']}
};
let selected='example_trader', windowKey='24h', compare=['example_trader','example_alex','example_casey'];
const $=s=>document.querySelector(s), money=n=>`${n>=0?'+':'-'}$${Math.abs(n).toLocaleString()}`;
function renderGraph(){const t=traders[selected],ids=[selected,...t.connections.filter(x=>traders[x])],pos=[[50,52],[24,31],[77,29],[74,76]],g=$('#graph');g.innerHTML='';ids.forEach((id,i)=>{const[x,y]=pos[i],n=traders[id],b=document.createElement('button');b.className=`node ${id===selected?'selected':''}`;b.style.left=x+'%';b.style.top=y+'%';b.innerHTML=`<span class="circle">${n.initials}</span><b>@${id.replace('example_','')}</b><small>${money(n.pnl['7d'])} / 7D</small>`;b.onclick=()=>{selected=id;if(!compare.includes(id))compare=[id,...compare].slice(0,3);render()};g.appendChild(b)});ids.slice(1).forEach((id,i)=>{const[x1,y1]=pos[0],[x2,y2]=pos[i+1],e=document.createElement('i');e.className='edge';e.style.left=x1+'%';e.style.top=y1+'%';e.style.width=Math.hypot(x2-x1,y2-y1)+'%';e.style.transform=`rotate(${Math.atan2(y2-y1,x2-x1)}rad)`;g.insertBefore(e,g.firstChild)})}
function renderDossier(){const t=traders[selected];$('#dossier').innerHTML=`<div class="dossier-top"><div><div class="avatar">${t.initials}</div><div class="handle">@${selected}</div><div class="name">${t.name} <span class="verified">◆</span></div></div><div class="mini-score"><strong>${t.score}</strong><span>RESEARCH SIGNAL</span></div></div><div class="divider"></div><div class="dossier-kicker">Profile totals</div><div class="detail-row"><span>Recorded trades</span><span>${t.trades}</span></div><div class="detail-row"><span>Followers</span><span>${t.followers}</span></div><div class="detail-row"><span>Last observation</span><span>${t.freshness}</span></div><div class="divider"></div><div class="dossier-kicker">Available wallet mappings</div>${t.wallets.map(w=>`<div class="wallet"><span class="chain">${w[0]}</span><span class="address">${w[1]}</span></div>`).join('')}`}
function renderPnl(){const t=traders[selected],value=t.pnl[windowKey];$('#pnlCard').innerHTML=`<div class="pnl-header"><div><div class="pnl-title">SAMPLED ${windowKey==='all'?'ALL-TIME':windowKey.toUpperCase()} PNL · USD</div><div class="pnl-value ${value>=0?'positive':''}">${money(value)}</div></div><div class="status"><i></i> stored sample</div></div><div class="chart"><div class="chart-grid"></div><svg viewBox="0 0 600 120" preserveAspectRatio="none"><defs><linearGradient id="fade" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#bafc58" stop-opacity=".25"/><stop offset="1" stop-color="#bafc58" stop-opacity="0"/></linearGradient></defs><path class="fill" d="M0 106 C70 100 80 80 135 89 S205 45 255 64 S320 50 370 54 S438 20 490 35 S550 10 600 12 V120 H0Z"/><path d="M0 106 C70 100 80 80 135 89 S205 45 255 64 S320 50 370 54 S438 20 490 35 S550 10 600 12"/></svg></div><div class="hero-note"><span class="pill">OBSERVED ${t.freshness.toUpperCase()}</span> Profile totals are independent of the selected window.</div>`}
function renderSignal(){const t=traders[selected],rows=[['Persistence across windows',Math.min(96,t.score+3)],['Observation freshness',t.freshness.includes('hr')?71:92],['Wallet coverage',t.wallets.length===2?94:66],['Network corroboration',Math.min(90,50+t.connections.length*12)]];$('#signalCard').innerHTML=`<div class="dossier-kicker">Why this trader surfaced</div><div class="signal-score">${t.score}</div><h3>Research signal</h3>${rows.map(r=>`<div class="bar"><div class="bar-head"><span>${r[0]}</span><span>${r[1]}</span></div><div class="bar-track"><div class="bar-fill" style="width:${r[1]}%"></div></div></div>`).join('')}`}
function renderCompare(){$('#compareGrid').innerHTML=compare.map(id=>{const t=traders[id];return `<div class="compare-item ${id===selected?'selected':''}"><div class="compare-name">@${id}</div><div class="compare-pnl ${t.pnl['7d']>=0?'positive':''}">${money(t.pnl['7d'])}</div><div class="compare-meta"><span>7D SAMPLED PNL</span><span>SIGNAL ${t.score}</span></div><button class="compare-action" data-id="${id}">Open dossier →</button></div>`}).join('');document.querySelectorAll('.compare-action').forEach(b=>b.onclick=()=>{selected=b.dataset.id;render();location.hash='map'})}
function render(){renderGraph();renderDossier();renderPnl();renderSignal();renderCompare();document.querySelectorAll('#windowTabs button').forEach(b=>b.classList.toggle('active',b.dataset.window===windowKey))}
$('#searchForm').onsubmit=e=>{e.preventDefault();const v=$('#handleInput').value.trim().replace(/^@/,'').toLowerCase();if(traders[v]){selected=v;render();location.hash='map'}else $('#handleInput').value='Try example_trader'};
document.querySelectorAll('#windowTabs button').forEach(b=>b.onclick=()=>{windowKey=b.dataset.window;renderPnl()});
$('#shareBtn').onclick=async()=>{const url=location.href.split('#')[0]+'#trader='+selected;try{await navigator.clipboard.writeText(url)}catch{}$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)};
const hash=location.hash.match(/trader=([^&]+)/);if(hash&&traders[hash[1]])selected=hash[1];render();
